language: java

jdk: oraclejdk8

android:
  components:
    - gradle-wrapper

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - cd Chess
  - chmod +x gradlew

deploy:
  provider: releases
  api_key: "5603117025011003aa1bd44ad063435f04c71e9d"
  file: "build/libs/Chess.jar"
  skip_cleanup: true
  on:
    tags: true
